SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SMALL_KIND = 1
MEDIUM_KIND = 2
LARGE_KIND = 3

LARGE_POINTS = 20
MEDIUM_POINTS = 50
SMALL_POINTS = 100

POINTS_PER_SECOND = 5

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MAX_SPEED = 400
PLAYER_ACCELERATION = 20
PLAYER_DECELERATION = 0.4
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

PLAYER1 = 1
PLAYER2 = 2

SHOT_RADIUS = 5